#!/usr/bin/env julia

using Printf
using TOML

const TARGETS = ("mx", "my", "mz")

function load_rows(path::AbstractString)
    parsed = TOML.parsefile(path)
    rows = NamedTuple[]
    for ch in get(parsed, "channels", Any[])
        push!(rows, (; observable=String(ch["observable"]),
            target=String(ch["target_component"]),
            rel_rmse=Float64(ch["rel_rmse"]),
            corr=Float64(ch["corr"]),
            data_rms=Float64(ch["data_rms"]),
            signal_fraction=Float64(ch["signal_fraction"]),
            source=String(get(ch, "source", basename(path)))))
    end
    return rows
end

function write_rows(path::AbstractString, rows::Vector{NamedTuple}, topk::Int, source::AbstractString)
    open(path, "w") do io
        println(io, "# Compact retained nonlinear observable channels.")
        println(io, "# Generated by code/make_compact_observable_channels.jl.")
        println(io, "# Source: $(basename(source)); top $(topk) per target component.")
        println(io, "# True M was used only in the upstream ex-post observable filtering, not in M training targets.")
        println(io, "corr_min = 0.9")
        println(io, "rel_rmse_max = 0.5")
        println(io, "signal_fraction_min = 0.05")
        println(io, "translation_offsets = \"all\"")
        println(io)
        for row in rows
            println(io, "[[channels]]")
            println(io, "observable = \"$(row.observable)\"")
            println(io, "target_component = \"$(row.target)\"")
            println(io, @sprintf("rel_rmse = %.8e", row.rel_rmse))
            println(io, @sprintf("corr = %.8f", row.corr))
            println(io, @sprintf("data_rms = %.8e", row.data_rms))
            println(io, @sprintf("signal_fraction = %.8e", row.signal_fraction))
            println(io, "source = \"$(row.source)\"")
            println(io)
        end
    end
end

function write_log(path::AbstractString, rows::Vector{NamedTuple}, topk::Int)
    open(path, "w") do io
        println(io, "Compact retained nonlinear observable channels")
        println(io, @sprintf("top per target: %d", topk))
        println(io, @sprintf("total channels: %d", length(rows)))
        println(io)
        for target in TARGETS
            subset = [row for row in rows if row.target == target]
            println(io, @sprintf("%s channels: %d", target, length(subset)))
            for row in subset
                println(io, @sprintf("  %-24s rel %.4f corr %.4f rms %.4e source %s",
                    row.observable, row.rel_rmse, row.corr, row.data_rms, row.source))
            end
            println(io)
        end
    end
end

function main()
    root = normpath(joinpath(@__DIR__, ".."))
    source = length(ARGS) >= 1 ? ARGS[1] :
        joinpath(root, "configs", "nonlinear_observable_retained_channels_merged.toml")
    topk = length(ARGS) >= 2 ? parse(Int, ARGS[2]) : 12
    suffix = length(ARGS) >= 3 ? ARGS[3] : "top$(topk)"
    rows = load_rows(source)
    selected = NamedTuple[]
    for target in TARGETS
        subset = sort([row for row in rows if row.target == target];
            by=row -> (row.rel_rmse, -row.corr, -row.data_rms, row.observable))
        append!(selected, subset[1:min(topk, length(subset))])
    end
    out_toml = joinpath(root, "configs", "nonlinear_observable_retained_channels_$(suffix).toml")
    out_log = joinpath(root, "logs", "nonlinear_observable_retained_channels_$(suffix).txt")
    write_rows(out_toml, selected, topk, source)
    write_log(out_log, selected, topk)
    @printf("Saved %d compact channels to %s\n", length(selected), out_toml)
    @printf("Saved compact-channel log to %s\n", out_log)
end

main()
