#!/usr/bin/env julia

using Printf
using TOML

function load_channels(path)
    parsed = TOML.parsefile(path)
    channels = get(parsed, "channels", Any[])
    out = NamedTuple[]
    for ch in channels
        push!(out, (; observable=String(ch["observable"]),
            target=String(ch["target_component"]),
            rel_rmse=Float64(ch["rel_rmse"]),
            corr=Float64(ch["corr"]),
            data_rms=Float64(ch["data_rms"]),
            signal_fraction=Float64(ch["signal_fraction"]),
            source=basename(path)))
    end
    return out
end

function main()
    root = normpath(joinpath(@__DIR__, ".."))
    inputs = [
        joinpath(root, "configs", "nonlinear_observable_retained_channels.toml"),
        joinpath(root, "configs", "nonlinear_observable_retained_channels_poly_high.toml"),
        joinpath(root, "configs", "nonlinear_observable_retained_channels_neighbor_high.toml"),
        joinpath(root, "configs", "nonlinear_observable_retained_channels_all.toml"),
    ]
    by_key = Dict{Tuple{String, String}, NamedTuple}()
    source_counts = Dict{String, Int}()
    for path in inputs
        isfile(path) || continue
        channels = load_channels(path)
        source_counts[basename(path)] = length(channels)
        for row in channels
            key = (row.observable, row.target)
            if !haskey(by_key, key) || row.rel_rmse < by_key[key].rel_rmse
                by_key[key] = row
            end
        end
    end
    rows = sort(collect(values(by_key)); by=row -> (row.target, row.rel_rmse, -row.corr, row.observable))
    out_toml = joinpath(root, "configs", "nonlinear_observable_retained_channels_merged.toml")
    out_log = joinpath(root, "logs", "nonlinear_observable_retained_channels_merged.txt")
    open(out_toml, "w") do io
        println(io, "# Merged retained nonlinear observable channels.")
        println(io, "# Generated by code/merge_retained_observable_channels.jl.")
        println(io, "# Channels passed ex-post data Cdot vs conditional-score + true-M operator filtering.")
        println(io, "# True M was used only for diagnostic filtering, not for a minimized training target.")
        println(io, "corr_min = 0.90000000")
        println(io, "rel_rmse_max = 0.50000000")
        println(io, "signal_fraction_min = 0.05000000")
        println(io, "translation_offsets = \"all\"")
        println(io)
        for row in rows
            println(io, "[[channels]]")
            println(io, "observable = \"$(row.observable)\"")
            println(io, "target_component = \"$(row.target)\"")
            println(io, @sprintf("rel_rmse = %.8e", row.rel_rmse))
            println(io, @sprintf("corr = %.8f", row.corr))
            println(io, @sprintf("data_rms = %.8e", row.data_rms))
            println(io, @sprintf("signal_fraction = %.8e", row.signal_fraction))
            println(io, "source = \"$(row.source)\"")
            println(io)
        end
    end
    open(out_log, "w") do io
        println(io, "Merged retained nonlinear observable channels")
        for (src, count) in sort(collect(source_counts))
            println(io, @sprintf("%-62s %d", src, count))
        end
        println(io, @sprintf("unique merged channels: %d", length(rows)))
        println(io)
        for target in ("mx", "my", "mz")
            subset = [row for row in rows if row.target == target]
            println(io, @sprintf("%s channels: %d", target, length(subset)))
            for row in subset[1:min(end, 25)]
                println(io, @sprintf("  %-24s rel %.4f corr %.4f rms %.4e source %s",
                    row.observable, row.rel_rmse, row.corr, row.data_rms, row.source))
            end
            println(io)
        end
    end
    @printf("Merged %d unique retained nonlinear observable-target channels.\n", length(rows))
    @printf("Saved %s\n", out_toml)
    @printf("Saved %s\n", out_log)
end

main()
