#!/usr/bin/env julia

include(joinpath(@__DIR__, "cond_score.jl"))

using LinearAlgebra
using Printf
using Statistics

function translation_profiles(Craw::Array{Float64, 4})
    nlags, nsites, nobs, dim = size(Craw)
    ncomp = 3
    profiles = zeros(Float64, nlags, nobs, ncomp, nsites)
    counts = zeros(Int, nsites)
    for i in 1:nsites, j in 1:nsites
        offset = mod(j - i, nsites) + 1
        counts[offset] += 1
        for c in 1:ncomp, a in 1:nobs, li in 1:nlags
            col = (j - 1) * ncomp + c
            profiles[li, a, c, offset] += Craw[li, i, a, col]
        end
    end
    for offset in 1:nsites
        profiles[:, :, :, offset] ./= counts[offset]
    end
    return profiles
end

function write_profile_metrics(path, names, compnames, data_prof, learn_prof)
    open(path, "w") do io
        println(io, "SoftSpinLLGChain best conditional score A all-profile Cdot metrics")
        for a in eachindex(names), c in eachindex(compnames)
            D = data_prof[:, a, c, :]
            L = learn_prof[:, a, c, :]
            rel = sqrt(mean((D .- L) .^ 2)) / sqrt(mean(D .^ 2))
            corr = dot(vec(D), vec(L)) / (norm(vec(D)) * norm(vec(L)))
            println(io, @sprintf("%-10s -> %-9s rel.RMSE %.8e corr %.8f",
                names[a], compnames[c], rel, corr))
        end
    end
end

function profile_metric_table(names, compnames, data_prof, learn_prof)
    rows = NamedTuple[]
    max_rms = 0.0
    for a in eachindex(names), c in eachindex(compnames)
        D = data_prof[:, a, c, :]
        max_rms = max(max_rms, sqrt(mean(D .^ 2)))
    end
    for a in eachindex(names), c in eachindex(compnames)
        D = data_prof[:, a, c, :]
        L = learn_prof[:, a, c, :]
        data_rms = sqrt(mean(D .^ 2))
        learn_rms = sqrt(mean(L .^ 2))
        rel = sqrt(mean((D .- L) .^ 2)) / max(data_rms, eps(Float64))
        corr = dot(vec(D), vec(L)) / max(norm(vec(D)) * norm(vec(L)), eps(Float64))
        push!(rows, (; obs_index=a, target_index=c, observable=names[a],
            target=compnames[c], rel_rmse=rel, corr=corr, data_rms=data_rms,
            learn_rms=learn_rms, signal_fraction=data_rms / max(max_rms, eps(Float64))))
    end
    return rows
end

function select_decent_channels(rows; corr_min=0.90, rel_max=0.50, signal_fraction_min=0.02)
    keep = Bool[]
    for row in rows
        push!(keep, row.corr >= corr_min &&
            row.rel_rmse <= rel_max &&
            row.signal_fraction >= signal_fraction_min)
    end
    return keep
end

function write_selection_metrics(path, rows, keep;
        corr_min=0.90, rel_max=0.50, signal_fraction_min=0.02)
    open(path, "w") do io
        println(io, "SoftSpinLLGChain retained conditional-score Cdot_mn channels")
        println(io, @sprintf("Selection: corr >= %.3f, rel.RMSE <= %.3f, data_rms >= %.3f of max data_rms",
            corr_min, rel_max, signal_fraction_min))
        println(io)
        for (row, iskeep) in zip(rows, keep)
            status = iskeep ? "KEEP" : "reject"
            reason = iskeep ? "accepted" :
                row.signal_fraction < signal_fraction_min ? "weak data signal" :
                row.corr < corr_min ? "bad shape correlation" :
                "large relative error"
            println(io, @sprintf("%-6s %-10s -> %-9s rel.RMSE %.8e corr %.8f data_rms %.8e signal_frac %.8e learn_rms %.8e  %s",
                status, row.observable, row.target, row.rel_rmse, row.corr,
                row.data_rms, row.signal_fraction, row.learn_rms, reason))
        end
    end
end

function write_selection_toml(path, rows, keep, cond_path, phi_path;
        corr_min=0.90, rel_max=0.50, signal_fraction_min=0.02)
    open(path, "w") do io
        println(io, "# Generated by code/plot_all_cond_cdot.jl.")
        println(io, "# Retained channels passed the ex-post conditional-score operator test")
        println(io, "# comparing data-driven Cdot_mn(t) with true-M acting on the learned transition residual.")
        println(io, "# True M was used only for this diagnostic/filter, not as a training target.")
        println(io, "source_cond_score = \"$(relpath(cond_path, dirname(path)))\"")
        println(io, "source_phi_artifacts = \"$(relpath(phi_path, dirname(path)))\"")
        println(io, @sprintf("corr_min = %.8f", corr_min))
        println(io, @sprintf("rel_rmse_max = %.8f", rel_max))
        println(io, @sprintf("signal_fraction_min = %.8f", signal_fraction_min))
        println(io, "translation_offsets = \"all\"")
        println(io)
        for (row, iskeep) in zip(rows, keep)
            iskeep || continue
            println(io, "[[channels]]")
            println(io, "observable = \"$(row.observable)\"")
            println(io, "target_component = \"$(replace(row.target, " target" => ""))\"")
            println(io, "observable_index = $(row.obs_index)")
            println(io, "target_component_index = $(row.target_index)")
            println(io, @sprintf("rel_rmse = %.8e", row.rel_rmse))
            println(io, @sprintf("corr = %.8f", row.corr))
            println(io, @sprintf("data_rms = %.8e", row.data_rms))
            println(io, @sprintf("signal_fraction = %.8e", row.signal_fraction))
            println(io)
        end
    end
end

function render_retained_figure(path, rows, keep, data_prof, learn_prof, taus)
    kept = findall(keep)
    isempty(kept) && error("No retained channels passed the configured thresholds")
    palette = Makie.wong_colors()
    ncols = min(3, length(kept))
    nrows = cld(length(kept), ncols)
    fig = Figure(; size=(1700 * ncols, 900 * nrows + 260))
    Label(fig[0, 1:ncols],
        "SoftSpinLLGChain conditional score A: retained Cdot_mn(t) profiles";
        fontsize=32, tellwidth=false)
    for (panel, idx) in enumerate(kept)
        row = rows[idx]
        gr = 1 + (panel - 1) ÷ ncols
        gc = 1 + (panel - 1) % ncols
        ax = Axis(fig[gr, gc];
            title=@sprintf("%s -> %s   rel %.3f corr %.3f",
                row.observable, row.target, row.rel_rmse, row.corr),
            xlabel="tau", ylabel="Cdot")
        for offset in axes(data_prof, 4)
            color = palette[mod1(offset, length(palette))]
            lines!(ax, taus, data_prof[:, row.obs_index, row.target_index, offset];
                color=(color, 0.9), linewidth=2.2)
            lines!(ax, taus, learn_prof[:, row.obs_index, row.target_index, offset];
                color=(color, 0.9), linewidth=2.2, linestyle=:dash)
        end
    end
    elems = [LineElement(; color=:black, linestyle=:solid, linewidth=3),
        LineElement(; color=:black, linestyle=:dash, linewidth=3)]
    Legend(fig[nrows + 1, 1:ncols], elems, ["data Cdot", "learned r with true-M"];
        orientation=:horizontal, tellwidth=false, tellheight=true,
        framevisible=false, labelsize=22)
    Label(fig[nrows + 2, 1:ncols],
        "Only channels passing corr >= 0.90, rel.RMSE <= 0.50, and data_rms >= 2% of the strongest channel are shown. Colors are the 12 translation offsets.";
        fontsize=20, tellwidth=false)
    save_figure_checked(path, fig)
end

function main()
    cond_path = joinpath(@__DIR__, "..", "models", "cond_score_residual_gpu0_vA.bson")
    phi_path = joinpath(@__DIR__, "..", "models", "fit_Phi_artifacts.bson")
    out_png = joinpath(@__DIR__, "..", "figures", "cond_score_gpu0_vA_all_Cdot_profiles.png")
    out_metrics = joinpath(@__DIR__, "..", "logs", "cond_score_gpu0_vA_all_Cdot_profiles_metrics.txt")
    retained_png = joinpath(@__DIR__, "..", "figures", "cond_score_gpu0_vA_retained_Cdot_profiles.png")
    retained_metrics = joinpath(@__DIR__, "..", "logs", "cond_score_gpu0_vA_retained_Cdot_profiles_metrics.txt")
    retained_toml = joinpath(@__DIR__, "..", "configs", "cond_score_gpu0_vA_retained_cdot_channels.toml")

    cond = BSON.load(cond_path)
    phi = BSON.load(phi_path)

    Cdata_full = Array{Float64}(phi[:Cdot_data])
    Clearn = Array{Float64}(cond[:diagnostics][:operator_trueM])
    nlags = size(Clearn, 1)
    Cdata = Cdata_full[1:nlags, :, :, :]
    taus = Vector{Float64}(cond[:diagnostics][:operator_lags])
    names = String.(phi[:observable_names])
    compnames = ["mx target", "my target", "mz target"]

    data_prof = translation_profiles(Cdata)
    learn_prof = translation_profiles(Clearn)
    write_profile_metrics(out_metrics, names, compnames, data_prof, learn_prof)
    rows = profile_metric_table(names, compnames, data_prof, learn_prof)
    corr_min = 0.90
    rel_max = 0.50
    signal_fraction_min = 0.02
    keep = select_decent_channels(rows; corr_min, rel_max, signal_fraction_min)
    write_selection_metrics(retained_metrics, rows, keep; corr_min, rel_max, signal_fraction_min)
    write_selection_toml(retained_toml, rows, keep, cond_path, phi_path;
        corr_min, rel_max, signal_fraction_min)

    nobs = length(names)
    ncomp = length(compnames)
    noffsets = size(data_prof, 4)
    palette = Makie.wong_colors()

    fig = Figure(; size=(5200, 3400))
    Label(fig[0, 1:ncomp],
        "SoftSpinLLGChain conditional score A: all translation-profile Cdot_mn(t)";
        fontsize=34, tellwidth=false)

    for a in 1:nobs, c in 1:ncomp
        D = data_prof[:, a, c, :]
        L = learn_prof[:, a, c, :]
        rel = sqrt(mean((D .- L) .^ 2)) / sqrt(mean(D .^ 2))
        corr = dot(vec(D), vec(L)) / (norm(vec(D)) * norm(vec(L)))
        ax = Axis(fig[a, c];
            title=@sprintf("%s -> %s   rel %.2f corr %.2f", names[a], compnames[c], rel, corr),
            xlabel=a == nobs ? "tau" : "",
            ylabel=c == 1 ? "Cdot" : "")
        for offset in 1:noffsets
            color = palette[mod1(offset, length(palette))]
            lines!(ax, taus, data_prof[:, a, c, offset];
                color=(color, 0.85), linewidth=1.8)
            lines!(ax, taus, learn_prof[:, a, c, offset];
                color=(color, 0.85), linewidth=1.8, linestyle=:dash)
        end
    end

    elems = [LineElement(; color=:black, linestyle=:solid, linewidth=3),
        LineElement(; color=:black, linestyle=:dash, linewidth=3)]
    Legend(fig[nobs + 1, 1:ncomp], elems, ["data Cdot", "learned r with true-M"];
        orientation=:horizontal, tellwidth=false, tellheight=true,
        framevisible=false, labelsize=24)
    Label(fig[nobs + 2, 1:ncomp],
        "Each panel overlays all 12 lattice offsets after translation averaging; colors identify offsets, solid=data, dashed=learned conditional-score operator.";
        fontsize=22, tellwidth=false)

    save_figure_checked(out_png, fig)
    render_retained_figure(retained_png, rows, keep, data_prof, learn_prof, taus)
    @printf("Saved all-profile Cdot figure to %s\n", out_png)
    @printf("Saved profile metrics to %s\n", out_metrics)
    @printf("Saved retained-profile Cdot figure to %s\n", retained_png)
    @printf("Saved retained-channel metrics to %s\n", retained_metrics)
    @printf("Saved retained-channel config to %s\n", retained_toml)
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
