#!/usr/bin/env julia

using Printf
using TOML

function toml_value(io, key::AbstractString, value)
    if value isa AbstractString
        println(io, "$(key) = \"$(value)\"")
    elseif value isa Vector
        print(io, "$(key) = [")
        for (i, v) in enumerate(value)
            i > 1 && print(io, ", ")
            if v isa AbstractString
                print(io, "\"$(v)\"")
            else
                print(io, v)
            end
        end
        println(io, "]")
    else
        println(io, "$(key) = $(value)")
    end
end

function write_clean_subset(input::AbstractString, output::AbstractString;
        rel_max::Float64, corr_min::Float64, max_channels::Int=0,
        sort_key::Symbol=:selected_rank)
    parsed = TOML.parsefile(input)
    channels = collect(get(parsed, "channels", Any[]))
    keep = [ch for ch in channels if
        Float64(ch["data_oracle_rel"]) <= rel_max &&
        Float64(ch["data_oracle_corr"]) >= corr_min]
    if sort_key == :selected_rank
        sort!(keep; by=ch -> Int(ch["selected_rank"]))
    elseif sort_key == :data_oracle_rel
        sort!(keep; by=ch -> Float64(ch["data_oracle_rel"]))
    elseif sort_key == :data_oracle_corr
        sort!(keep; by=ch -> -Float64(ch["data_oracle_corr"]))
    else
        error("Unsupported sort_key=$(sort_key)")
    end
    if max_channels > 0 && length(keep) > max_channels
        keep = keep[1:max_channels]
    end
    mkpath(dirname(output))
    open(output, "w") do io
        println(io, "# Clean subset of oracle-filtered observable channels.")
        println(io, "# Generated by code/select_clean_observable_subset.jl.")
        println(io, "# True M entered only the observable-library design diagnostic.")
        println(io, "source_retained_toml = \"$(basename(input))\"")
        println(io, "selection = \"data_oracle_rel_le_$(rel_max)_corr_ge_$(corr_min)_sort_$(sort_key)\"")
        println(io, "data_oracle_rel_max = $(rel_max)")
        println(io, "data_oracle_corr_min = $(corr_min)")
        println(io, "max_channels = $(max_channels)")
        println(io, "sort_key = \"$(sort_key)\"")
        println(io, "n_channels = $(length(keep))")
        println(io)
        for ch in keep
            println(io, "[[channels]]")
            for key in sort(collect(keys(ch)))
                toml_value(io, key, ch[key])
            end
            println(io)
        end
    end
    @printf("Wrote %d/%d channels to %s (rel <= %.4f, corr >= %.4f, sort=%s)\n",
        length(keep), length(channels), output, rel_max, corr_min, sort_key)
    return length(keep)
end

function main()
    length(ARGS) >= 4 || error("Usage: select_clean_observable_subset.jl input.toml output.toml rel_max corr_min [max_channels] [sort_key]")
    input = ARGS[1]
    output = ARGS[2]
    rel_max = parse(Float64, ARGS[3])
    corr_min = parse(Float64, ARGS[4])
    max_channels = length(ARGS) >= 5 ? parse(Int, ARGS[5]) : 0
    sort_key = length(ARGS) >= 6 ? Symbol(ARGS[6]) : :selected_rank
    write_clean_subset(input, output; rel_max, corr_min, max_channels, sort_key)
end

main()
