#!/usr/bin/env julia

using Printf
using TOML

function write_subset(input::AbstractString, output::AbstractString, keep::Int)
    parsed = TOML.parsefile(input)
    channels = collect(get(parsed, "channels", Any[]))
    sort!(channels; by=ch -> Int(get(ch, "selected_rank", typemax(Int))))
    kept = channels[1:min(keep, length(channels))]
    mkpath(dirname(output))
    open(output, "w") do io
        println(io, "# Strongest subset of generalized right-observable channels.")
        println(io, "# Generated by code/select_right_observable_subset.jl.")
        println(io, "# IMPORTANT: parent library was selected with true M; this is oracle-only.")
        println(io, "source_file = \"$(input)\"")
        println(io, "subset_rule = \"selected_rank <= $(keep)\"")
        println(io, "target_kind = \"oracle_trueM_rightobs_identifiability_subset\"")
        for (key, value) in parsed
            key in ("channels", "target_kind") && continue
            if value isa AbstractString
                println(io, "$(key) = \"$(value)\"")
            elseif value isa Integer || value isa AbstractFloat
                println(io, "$(key) = $(value)")
            end
        end
        println(io)
        for ch in kept
            println(io, "[[channels]]")
            for key in sort(collect(keys(ch)))
                val = ch[key]
                if val isa AbstractString
                    println(io, "$(key) = \"$(val)\"")
                elseif val isa Vector
                    println(io, "$(key) = [$(join(val, ", "))]")
                else
                    println(io, "$(key) = $(val)")
                end
            end
            println(io)
        end
    end
    @printf("Wrote %d/%d channels to %s\n", length(kept), length(channels), output)
end

if abspath(PROGRAM_FILE) == @__FILE__
    length(ARGS) >= 3 || error("Usage: select_right_observable_subset.jl input.toml output.toml keep")
    write_subset(ARGS[1], ARGS[2], parse(Int, ARGS[3]))
end
